#include "localVariables.h"
#include <zephyr/kernel.h>

K_FIFO_DEFINE(PMODKYPD_fifo);
K_FIFO_DEFINE(ULTRASONIC_fifo);
K_FIFO_DEFINE(MAGNETOMETER_fifo);
K_FIFO_DEFINE(ULTRASONIC_SAMPLE_fifo);
K_FIFO_DEFINE(MAGNETOMETER_SAMPLE_fifo);